spring.application.name=SpringAIDemo
spring.ai.google.genai.api-key=AIzaSyCPLIxYL9-H84uzY4RYOkNfrMAhugqAmoQ

spring.datasource.url=jdbc:h2:mem:sessiondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.data.dir=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS\\ASCII
app.copybook.dir=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS\\copybooks
app.output.dir=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS\\converted-data
app.sql.output=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS\\sql
app.data.ebcdic=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS\\EBCDIC
app.data.csv=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS\\csv
app.copybook.intermediate=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS\\generated-inter-cpy
app.base.location=C:\\Users\\Rohit\\Documents\\VSAMtoRDBMS
app.template.location=C:\\Users\\Rohit\\Documents\\template